name: Test flask server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build a Docker image
        run: docker build -t dockertask:latest .

      - name: Run a Docker container
        run: docker run -d -p 8080:8080 dockertask:latest

      - name: Wait for server to start
        run: sleep 5  
        
      - name: Run a client
        run: python client.py

    
    
  
